Allow options to be passed into Ping
swissmanu/harmonyhubjs-discover pull request #8
Opened 2017-12-16 16:23 UTC by stblassitude

This allows users to specify the broadcast address to send the ping to.
This is neccessary on systems with more than one interface, or certain
operating systems.

This allows KraigM/homebridge-harmonyhub#105 to be addressed.

2017-12-19 07:02 UTC, swissmanu commented
thank you for your addition @stblassitude! glad you can make use of `harmonyhubjs-discover` :)

after going through your change, may i kindly ask you to have a look at the following points?

* would you please have a look at my review comments?
* `harmonyhubjs-discover` is prepared for [conventional-changelog commits using commitizen](https://github.com/commitizen/cz-cli) which allows simplified/automated publish of new module versions. please rephrase your commits accordingly.

again, thank you for your contribution

2017-12-19 07:02 UTC, swissmanu requested changes
thank you for your addition @stblassitude! glad you can make use of `harmonyhubjs-discover` :)

after going through your change, may i kindly ask you to have a look at the following points?

* would you please have a look at my review comments?
* `harmonyhubjs-discover` is prepared for [conventional-changelog commits using commitizen](https://github.com/commitizen/cz-cli) which allows simplified/automated publish of new module versions. please rephrase your commits accordingly.

again, thank you for your contribution

2017-12-19 07:02 UTC, swissmanu commented on lib/explorer.js
> +function Explorer (port, options) {
i'd suggest to rename `options` to `pingOptions`. (two times `port` for example might be a bit confusing :) )

2017-12-19 07:02 UTC, swissmanu commented on lib/ping.js
>    debug('Ping(' + portToAnnounce + ')')
what do you think about logging all new options here too?

2017-12-19 20:47 UTC, stblassitude commented
Can I use Commitizen to rework this PR? Or do I need to close this and redo the commits on a fresh branch, and submit a fresh PR?

2017-12-19 20:55 UTC, swissmanu commented
i dont have any problem if you force-push your rebased changes to this PR ☺️

2017-12-19 21:31 UTC, stblassitude commented
Let me know if this is acceptable, or needs further refinement.

2017-12-20 14:22 UTC, swissmanu approved these changes

2017-12-20 14:23 UTC, merged

2017-12-20 14:24 UTC, swissmanu commented
perfect, thanks for reworking :)
will release a new version asap

2017-12-20 15:03 UTC, swissmanu commented
latest release [v1.1.1](https://github.com/swissmanu/harmonyhubjs-discover/releases/tag/v1.1.1) is available with your changes 🙌

2017-12-20 15:34 UTC, stefanbethke commented
Thank you!

2017-12-20 15:38 UTC, stblassitude commented
Thank you!